[package]
org = "ballerina"
name = "connector_tool"
version = "0.1.1"
authors = ["Ballerina"]
keywords = ["connector", "connector tool", "connector generator"]
license = ["Apache-2.0"]
distribution = "2201.13.0"
