// Copyright (c) 2026 WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/io;
import ballerina/time;

import wso2/connector_automator.utils;

# Generate a Ballerina API Specification from raw sdk_analyzer metadata.
# This is the primary entry point for the module.
#
# + config - Generator configuration
# + return - GeneratorResult on success or GeneratorError on failure
public function generateSpecification(GeneratorConfig config) returns GeneratorResult|GeneratorError {
    time:Utc startTime = time:utcNow();

    printGeneratorPlan(config);

    // Step 1: Initialize AI service (validates ANTHROPIC_API_KEY)
    error? aiInit = utils:initAIService();
    if aiInit is error {
        return error GeneratorError("ANTHROPIC_API_KEY environment variable not set. " +
                                    "LLM is required for IR generation.");
    }

    // Step 2: Generate Intermediate Representation via LLM
    printGeneratorStep(1, "Generating Intermediate Representation via LLM", config.quietMode);

    IntermediateRepresentation|error irResult = generateIRFromMetadata(config.metadataPath, config);
    if irResult is error {
        return error GeneratorError(
            string `LLM IR generation failed: ${irResult.message()}`,
            irResult);
    }
    IntermediateRepresentation ir = irResult;

    if !config.quietMode {
        io:fprintln(io:stderr, string `  → ${ir.functions.length()} functions, ` +
                    string `${ir.structures.length()} structures, ` +
                    string `${ir.enums.length()} enums, ` +
                    string `${ir.collections.length()} collections`);
    }

    // Step 3: Save IR JSON to file for reference / inspection
    string datasetToken = config.datasetKey.trim().length() > 0 ? config.datasetKey.trim() :
        ir.clientName.toLowerAscii();
    string irFileName = string `${datasetToken}-ir.json`;
    string? irPath = ();

    json|error irJson = ir.cloneWithType(json);
    if irJson is json {
        string|error irWriteResult = writeIRJsonFile(irJson, config.outputDir, irFileName);
        if irWriteResult is string {
            irPath = irWriteResult;
            if !config.quietMode {
                io:fprintln(io:stderr, string `  → IR saved to ${irWriteResult}`);
            }
        } else if !config.quietMode {
            io:fprintln(io:stderr, string `  ⚠ Failed to save IR JSON: ${irWriteResult.message()}`);
        }
    } else if !config.quietMode {
        io:fprintln(io:stderr, string `  ⚠ Failed to serialize IR JSON: ${irJson.message()}`);
    }

    // Step 4: Build Ballerina specification from IR (manual code generation)
    printGeneratorStep(2, "Building Ballerina specification from IR", config.quietMode);

    string ballerinaCode = buildSpec(ir);

    // Add auto-generation header
    string header = "// Auto-generated Ballerina API Specification\n" +
                    string `// SDK: ${ir.sdkName} ${ir.version}` + "\n" +
                    string `// Client: ${ir.clientName}` + "\n" +
                    "// Generated by: Connector Automator\n\n";
    ballerinaCode = header + ballerinaCode;

    // Step 5: Write the specification file
    printGeneratorStep(3, "Writing specification file", config.quietMode);
    string specFileName = string `${datasetToken}_spec.bal`;
    string|error writeResult = writeBallerinaSpec(ballerinaCode, config.outputDir, specFileName);
    if writeResult is error {
        return error GeneratorError(
            string `Failed to write specification file: ${writeResult.message()}`,
            writeResult);
    }
    string specPath = writeResult;

    if !config.quietMode {
        io:fprintln(io:stderr, string `  → Specification written to ${specPath}`);
    }

    // Step 6: Run bal format
    printGeneratorStep(4, "Formatting specification", config.quietMode);
    error? fmtResult = runBalFormat(specPath);
    if fmtResult is error {
        if !config.quietMode {
            io:fprintln(io:stderr, string `  → Formatting warning: ${fmtResult.message()}`);
        }
    } else {
        if !config.quietMode {
            io:fprintln(io:stderr, "  → Formatted successfully");
        }
    }

    // Calculate duration
    time:Utc endTime = time:utcNow();
    decimal duration = time:utcDiffSeconds(endTime, startTime);
    int durationMs = <int>(duration * 1000);

    if !config.quietMode {
        printGeneratorSummary(specPath, irPath, duration);
    }

    return {
        success: true,
        specificationPath: specPath,
        irPath: irPath,
        durationMs: durationMs
    };
}

function printGeneratorPlan(GeneratorConfig config) {
    if config.quietMode {
        return;
    }
    string sep = createGeneratorSeparator("=", 70);
    io:fprintln(io:stderr, sep);
    io:fprintln(io:stderr, "API Specification Generation Plan");
    io:fprintln(io:stderr, sep);
    io:fprintln(io:stderr, string `Metadata: ${config.metadataPath}`);
    io:fprintln(io:stderr, string `Output Dir: ${config.outputDir}`);
    io:fprintln(io:stderr, "");
    io:fprintln(io:stderr, "Operations:");
    io:fprintln(io:stderr, "  1. Generate Intermediate Representation via LLM");
    io:fprintln(io:stderr, "  2. Build Ballerina specification from IR");
    io:fprintln(io:stderr, "  3. Write and format generated specification");
    io:fprintln(io:stderr, sep);
}

function printGeneratorSummary(string specPath, string? irPath, decimal duration) {
    string sep = createGeneratorSeparator("=", 70);
    io:fprintln(io:stderr, "");
    io:fprintln(io:stderr, sep);
    io:fprintln(io:stderr, "✓ API Specification Generation Complete");
    io:fprintln(io:stderr, sep);
    io:fprintln(io:stderr, string `  • specification: ${specPath}`);
    if irPath is string {
        io:fprintln(io:stderr, string `  • ir: ${<string>irPath}`);
    }
    io:fprintln(io:stderr, string `  • duration: ${duration}s`);
    io:fprintln(io:stderr, sep);
}

function printGeneratorStep(int stepNum, string title, boolean quietMode) {
    if quietMode {
        return;
    }
    string sep = createGeneratorSeparator("-", 50);
    io:fprintln(io:stderr, "");
    io:fprintln(io:stderr, string `Step ${stepNum}: ${title}`);
    io:fprintln(io:stderr, sep);
}

function createGeneratorSeparator(string char, int length) returns string {
    string[] chars = [];
    int i = 0;
    while i < length {
        chars.push(char);
        i += 1;
    }
    return string:'join("", ...chars);
}
