// Copyright (c) 2026 WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied. See the License for the
// specific language governing permissions and limitations
// under the License.

import wso2/connector_automator.utils;

import ballerina/file;
import ballerina/io;
import ballerina/lang.regexp;

function generateMockServer(string connectorPath, string specPath) returns error? {
    string ballerinaDir = check utils:resolveBallerinaDir(connectorPath);
    string testsDir = ballerinaDir + "/tests";
    int operationCount = check countOperationsInSpec(specPath);
    utils:logVerbose(string `total operations in spec: ${operationCount}`);

    string absSpecPath = check file:getAbsolutePath(specPath);
    string absTestsDir = check file:getAbsolutePath(testsDir);

    check file:createDir(testsDir, file:RECURSIVE);

    string command;

    if operationCount <= MAX_OPERATIONS {
        utils:logVerbose(string `using all ${operationCount} operations`);
        command = string `bal openapi -i ${absSpecPath} --mode service -o ${absTestsDir}`;
    } else {
        utils:logVerbose(string `filtering from ${operationCount} to ${MAX_OPERATIONS} most useful operations`);
        string operationsList = check selectOperationsUsingAI(specPath);
        utils:logVerbose(string `selected operations: ${operationsList}`);
        command = string `bal openapi -i ${absSpecPath} --mode service -o ${absTestsDir} --operations ${operationsList}`;
    }

    utils:CommandResult result = utils:executeCommand(command, ballerinaDir);
    if !result.success {
        return error("Failed to generate mock server using ballerina openAPI tool" + result.stderr);
    }

    // Rename the generated service scaffold to mock_service.bal
    string serviceFileOld = testsDir + "/aligned_ballerina_openapi_service.bal";
    string serviceFileNew = testsDir + "/mock_service.bal";
    if check file:test(serviceFileOld, file:EXISTS) {
        check file:rename(serviceFileOld, serviceFileNew);
        utils:logVerbose("renamed service file to mock_service.bal");
    }

    // Remove the types.bal generated by bal openapi — root types.bal is used directly
    string generatedTypesPath = testsDir + "/types.bal";
    if check file:test(generatedTypesPath, file:EXISTS) {
        check file:remove(generatedTypesPath, file:RECURSIVE);
        utils:logVerbose("removed generated types.bal from tests/ (root types.bal used instead)");
    }
}

function countOperationsInSpec(string specPath) returns int|error {
    string specContent = check io:fileReadString(specPath);
    regexp:RegExp operationIdPattern = re `"operationId"\s*:\s*"[^"]*"`;
    regexp:Span[] matches = operationIdPattern.findAll(specContent);
    return matches.length();
}
